apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: reverse-proxy
spec:
  version: {{ .TagName }}
  homepage: https://github.com/rajatjindal/kubectl-reverse-proxy
  shortDescription: Start reverse proxy for the Service pods.
  description: |
    Runs the reverse proxy locally and route traffic to all pods behind the given service object. 
    
    It is different from the existing proxy plugins in that it starts a reverse proxy locally (instead of e.g. starting a socat proxy pod in the cluster) and 
    updates the backend config of that reverse proxy (currently using caddy) by doing port-forwarding and adding those listeners as backends.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/rajatjindal/kubectl-reverse-proxy/releases/download/{{ .TagName }}/kubectl-reverse-proxy_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    bin: kubectl-reverse_proxy
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/rajatjindal/kubectl-reverse-proxy/releases/download/{{ .TagName }}/kubectl-reverse-proxy_{{ .TagName }}_darwin_arm64.tar.gz" .TagName }}
    bin: kubectl-reverse_proxy
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/rajatjindal/kubectl-reverse-proxy/releases/download/{{ .TagName }}/kubectl-reverse-proxy_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    bin: kubectl-reverse_proxy
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/rajatjindal/kubectl-reverse-proxy/releases/download/{{ .TagName }}/kubectl-reverse-proxy_{{ .TagName }}_linux_arm64.tar.gz" .TagName }}
    bin: kubectl-reverse_proxy
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/rajatjindal/kubectl-reverse-proxy/releases/download/{{ .TagName }}/kubectl-reverse-proxy_{{ .TagName }}_windows_amd64.tar.gz" .TagName }}
    bin: kubectl-reverse_proxy.exe
