name: Test Pull Request
on: [pull_request]
jobs:
  TestPR:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        cache: true

    - name: Run unit tests
      run: |
        go test ./... -cover

